config/routes.rb
Rat3::Application.routes.draw do
  resources :organizations do
    resources :boards do
      resources :sales
    end
  end

  resources :customers do
    get 'search', on: :collection
  end

  resources :boards

  resources :sales

  devise_for :users

  root 'home#index'

  get  'events' => 'events#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :organization
  has_many :warehouses, :dependent => :destroy
  has_many :grades, :through => :warehouses
  has_many :sales, :through => :grades


  accepts_nested_attributes_for :warehouses

  def active_model_serializer
    BoardSerializer
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  load_and_authorize_resource

  before_action :set_organization
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = @organization.boards
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    respond_to do |format|
      format.html { }
      format.json { render :json => @board }
    end
  end

  # GET /boards/new
  def new
    @board = @organization.boards.build
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = @organization.boards.build(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to [@organization, @board], notice: 'Board was successfully created.' }
        format.json { render action: 'show', status: :created, location: @board }
      else
        format.html { render action: 'new' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to [@organization, @board], notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :no_content }
    end
  end

  private
    def set_organization
      @organization = Organization.find(params[:organization_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:date, :organization_id, :warehouses => [:name])
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for([@organization, @board]) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', [@organization, @board] %> |
<%= link_to 'Back', organization_boards_path(@organization) %>

app/views/boards/index.html.erb
<h1>Listing boards for <%= @organization.name %></h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Organization</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.date %></td>
        <td><%= board.organization_id %></td>
        <td><%= link_to 'Show', [@organization, board] %></td>
        <td><%= link_to 'Edit', edit_organization_board_path(@organization, board) %></td>
        <td><%= link_to 'Destroy', organization_board_path(@organization, board), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_organization_board_path(@organization) %>

app/views/boards/new.html.erb
<ng-view></ng-view>

app/views/boards/show.html.erb
<% content_for :header_text do %>
  <%= @organization.name %> for <%= @board.date %>
<% end %>

<div id="initial_object" data-board="<%= json_for @board %>" data-current_user="<%= json_for current_user %>"></div>
<ng-view></ng-view>